// Auto-generated data from schedule.csv and events.csv
const ITINERARY = [
  {
    "date": "25/06/2026",
    "time_slot": "Sáng",
    "stop_order": 1,
    "location_name": "Sân bay Quốc tế Đà Nẵng",
    "category": "Di chuyển",
    "address": "Nguyễn Văn Linh, Hòa Thuận Tây, Hải Châu, Đà Nẵng",
    "start_time": "08:00",
    "end_time": "08:30",
    "duration_minutes": 30,
    "cost_estimate": 0,
    "rating": 4.4,
    "tiktok_popularity": "Trung bình",
    "distance_to_next": "1.5 km (5 phút di chuyển)",
    "reason": "Điểm khởi đầu chuyến hành trình Đà Nẵng, làm thủ tục nhận hành lý và di chuyển vào trung tâm.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sân+bay+Quốc+tế+Đà+Nẵng"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Sáng",
    "stop_order": 2,
    "location_name": "Trình Cà Phê",
    "category": "Cafe",
    "address": "34/4 Nguyễn Hữu Thọ, Hòa Thuận Tây, Hải Châu, Đà Nẵng",
    "start_time": "08:30",
    "end_time": "09:30",
    "duration_minutes": 60,
    "cost_estimate": 30000,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "2.2 km (7 phút di chuyển)",
    "reason": "Quán cafe phong cách vườn mộc mạc, nhiều mảng xanh, cực kỳ chill để thư giãn sau chuyến bay.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Trình+Cà+Phê+Nguyễn+Hữu+Thọ+Đà+Nẵng"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Sáng",
    "stop_order": 3,
    "location_name": "Bảo tàng Điêu khắc Chăm Đà Nẵng",
    "category": "Du lịch",
    "address": "Số 2 đường 2 Tháng 9, Bình Hiên, Hải Châu, Đà Nẵng",
    "start_time": "09:30",
    "end_time": "11:00",
    "duration_minutes": 90,
    "cost_estimate": 60000,
    "rating": 4.5,
    "tiktok_popularity": "Trung bình",
    "distance_to_next": "0.8 km (3 phút di chuyển)",
    "reason": "Tìm hiểu văn hóa Chăm Pa cổ xưa với bộ sưu tập hiện vật điêu khắc đá độc bản lớn nhất thế giới.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bảo+tàng+Chăm+Đà+Nẵng"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Trưa",
    "stop_order": 4,
    "location_name": "Mì Quảng Bà Mua",
    "category": "Ăn uống",
    "address": "19-21 Trần Bình Trọng, Phước Ninh, Hải Châu, Đà Nẵng",
    "start_time": "11:00",
    "end_time": "12:00",
    "duration_minutes": 60,
    "cost_estimate": 50000,
    "rating": 4.5,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "0.3 km (1 phút đi bộ)",
    "reason": "Thương hiệu mì Quảng trứ danh, nước dùng ngọt đậm đà, thịt heo và tôm tươi ngon chuẩn vị.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Mì+Quảng+Bà+Mua+Trần+Bình+Trọng"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Trưa",
    "stop_order": 5,
    "location_name": "Nhà thờ Con Gà (Chính Tòa Đà Nẵng)",
    "category": "Check-in",
    "address": "156 Trần Phú, Hải Châu 1, Hải Châu, Đà Nẵng",
    "start_time": "12:00",
    "end_time": "13:00",
    "duration_minutes": 60,
    "cost_estimate": 0,
    "rating": 4.5,
    "tiktok_popularity": "Cao",
    "distance_to_next": "0.4 km (2 phút đi bộ)",
    "reason": "Nhà thờ kiến trúc Gothic cổ kính sơn màu hồng pastel duy nhất từ thời Pháp, điểm check-in sống ảo cực đẹp.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Nhà+thờ+Con+Gà+Đà+Nẵng"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Trưa",
    "stop_order": 6,
    "location_name": "Namto House Coffee",
    "category": "Cafe",
    "address": "130 Nguyễn Chí Thanh, Hải Châu 1, Hải Châu, Đà Nẵng",
    "start_time": "13:00",
    "end_time": "14:00",
    "duration_minutes": 60,
    "cost_estimate": 45000,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "9 km (15 phút di chuyển)",
    "reason": "Không gian tone màu gỗ ấm cúng phong cách Hàn Quốc siêu tinh tế, đồ uống ngọt mát nghỉ trưa dễ chịu.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Namto+House+Coffee+130+Nguyễn+Chí+Thanh"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Chiều",
    "stop_order": 7,
    "location_name": "Danh thắng Ngũ Hành Sơn",
    "category": "Du lịch",
    "address": "81 Huyền Trân Công Chúa, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng",
    "start_time": "14:00",
    "end_time": "16:30",
    "duration_minutes": 150,
    "cost_estimate": 60000,
    "rating": 4.5,
    "tiktok_popularity": "Cao",
    "distance_to_next": "7.5 km (12 phút di chuyển)",
    "reason": "Khám phá hang động kỳ bí (Động Huyền Không, Tàng Chơn) và viếng chùa Linh Ứng cổ kính giữa núi đá vôi.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Ngũ+Hành+Sơn+Đà+Nẵng"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Chiều",
    "stop_order": 8,
    "location_name": "Bãi biển Mỹ Khê",
    "category": "Check-in",
    "address": "Đường Võ Nguyên Giáp, Phước Mỹ, Sơn Trà, Đà Nẵng",
    "start_time": "16:30",
    "end_time": "18:00",
    "duration_minutes": 90,
    "cost_estimate": 0,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "1.2 km (3 phút di chuyển)",
    "reason": "Tắm biển mát lạnh, đi dạo trên bờ cát trắng mịn màng của một trong những bãi biển đẹp nhất hành tinh.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Biển+Mỹ+Khê+Đà+Nẵng"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Tối",
    "stop_order": 9,
    "location_name": "Hải sản Mộc Quán",
    "category": "Ăn uống",
    "address": "26 Tô Hiến Thành, Phước Mỹ, Sơn Trà, Đà Nẵng",
    "start_time": "18:00",
    "end_time": "19:30",
    "duration_minutes": 90,
    "cost_estimate": 250000,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "2.5 km (5 phút di chuyển)",
    "reason": "Thưởng thức hải sản tươi rói bắt tại bể, không gian quán mộc mạc và chế biến đậm đà nổi tiếng TikTok.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Mộc+Quán+Đà+Nẵng"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Tối",
    "stop_order": 10,
    "location_name": "Cầu Tình Yêu & Tượng Cá Chép Hóa Rồng",
    "category": "Check-in",
    "address": "Đường Trần Hưng Đạo, An Hải Tây, Sơn Trà, Đà Nẵng",
    "start_time": "19:30",
    "end_time": "21:00",
    "duration_minutes": 90,
    "cost_estimate": 0,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "0.1 km (1 phút đi bộ)",
    "reason": "Đi dạo ngắm sông Hàn thơ mộng lung linh ánh đèn, check-in cây cầu tình yêu khóa lãng mạn.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Cầu+Tình+Yêu+Đà+Nẵng"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Tối",
    "stop_order": 11,
    "location_name": "Chợ đêm Sơn Trà",
    "category": "Vui chơi",
    "address": "Đường Trần Hưng Đạo, An Hải Tây, Sơn Trà, Đà Nẵng",
    "start_time": "21:00",
    "end_time": "22:30",
    "duration_minutes": 90,
    "cost_estimate": 50000,
    "rating": 4.4,
    "tiktok_popularity": "Cao",
    "distance_to_next": "2.1 km (5 phút di chuyển)",
    "reason": "Mua sắm quà lưu niệm và ăn vặt tại khu chợ đêm nhộn nhịp ngay chân Cầu Rồng.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Chợ+đêm+Sơn+Trà"
  },
  {
    "date": "25/06/2026",
    "time_slot": "Tối",
    "stop_order": 12,
    "location_name": "On The Radio Bar",
    "category": "Vui chơi",
    "address": "76 Thái Phiên, Phước Ninh, Hải Châu, Đà Nẵng",
    "start_time": "22:30",
    "end_time": "23:30",
    "duration_minutes": 60,
    "cost_estimate": 100000,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "1.5 km (5 phút về khách sạn)",
    "reason": "Nghe ban nhạc live-music biểu diễn cực chất các bản hit acoustic và rock cuốn hút.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=On+The+Radio+Bar+Đà+Nẵng"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Sáng",
    "stop_order": 1,
    "location_name": "Bún chả cá Ông Tạ",
    "category": "Ăn uống",
    "address": "113A Nguyễn Chí Thanh, Hải Châu 1, Hải Châu, Đà Nẵng",
    "start_time": "07:00",
    "end_time": "08:00",
    "duration_minutes": 60,
    "cost_estimate": 45000,
    "rating": 4.5,
    "tiktok_popularity": "Cao",
    "distance_to_next": "26 km (45 phút di chuyển)",
    "reason": "Bắt đầu ngày mới với bát bún chả cá thu thơm ngon, ngọt thanh từ rau củ hầm chuẩn vị Đà Nẵng.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bún+chả+cá+Ông+Tạ+Đà+Nẵng"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Sáng",
    "stop_order": 2,
    "location_name": "Di chuyển lên Sun World Ba Na Hills",
    "category": "Di chuyển",
    "address": "An Sơn, Hòa Ninh, Hòa Vang, Đà Nẵng",
    "start_time": "08:00",
    "end_time": "09:00",
    "duration_minutes": 60,
    "cost_estimate": 150000,
    "rating": 4.6,
    "tiktok_popularity": "Trung bình",
    "distance_to_next": "0 km (tại điểm đến)",
    "reason": "Di chuyển bằng taxi/xe trung chuyển lên ga cáp treo Bà Nà Hills.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sun+World+Ba+Na+Hills"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Sáng",
    "stop_order": 3,
    "location_name": "Cáp treo & Check-in Cầu Vàng",
    "category": "Check-in",
    "address": "Sun World Ba Na Hills, Hòa Vang, Đà Nẵng",
    "start_time": "09:00",
    "end_time": "11:30",
    "duration_minutes": 150,
    "cost_estimate": 950000,
    "rating": 4.7,
    "tiktok_popularity": "Cực cao",
    "distance_to_next": "0 km (trong khu du lịch)",
    "reason": "Trải nghiệm cáp treo ngắm núi rừng xanh ngát và check-in Cầu Vàng nâng đỡ bởi bàn tay khổng lồ huyền thoại.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sun+World+Ba+Na+Hills"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Trưa",
    "stop_order": 4,
    "location_name": "Buffet trưa tại Arapang / Beer Plaza",
    "category": "Ăn uống",
    "address": "Khu ẩm thực Sun World Ba Na Hills, Hòa Vang, Đà Nẵng",
    "start_time": "11:30",
    "end_time": "13:00",
    "duration_minutes": 90,
    "cost_estimate": 350000,
    "rating": 4.5,
    "tiktok_popularity": "Cao",
    "distance_to_next": "0 km (trong khu du lịch)",
    "reason": "Thưởng thức ẩm thực buffet phong phú đa dạng quốc tế ngay trên đỉnh núi Bà Nà mát mẻ.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sun+World+Ba+Na+Hills"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Trưa",
    "stop_order": 5,
    "location_name": "Check-in Làng Pháp cổ kính",
    "category": "Check-in",
    "address": "Sun World Ba Na Hills, Hòa Vang, Đà Nẵng",
    "start_time": "13:00",
    "end_time": "14:00",
    "duration_minutes": 60,
    "cost_estimate": 0,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "0 km (trong khu du lịch)",
    "reason": "Chụp ảnh cùng lâu đài mang kiến trúc châu Âu Gothic trung cổ lãng mạn phủ sương mù tuyệt đẹp.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sun+World+Ba+Na+Hills"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Chiều",
    "stop_order": 6,
    "location_name": "Khu vui chơi Fantasy Park",
    "category": "Vui chơi",
    "address": "Sun World Ba Na Hills, Hòa Vang, Đà Nẵng",
    "start_time": "14:00",
    "end_time": "15:30",
    "duration_minutes": 90,
    "cost_estimate": 0,
    "rating": 4.5,
    "tiktok_popularity": "Cao",
    "distance_to_next": "0.1 km (1 phút đi bộ)",
    "reason": "Trải nghiệm khu vui chơi trong nhà khổng lồ với các trò chơi mạo hiểm cảm giác mạnh lý thú.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sun+World+Ba+Na+Hills"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Chiều",
    "stop_order": 7,
    "location_name": "Trượt máng Alpine Coaster",
    "category": "Vui chơi",
    "address": "Sun World Ba Na Hills, Hòa Vang, Đà Nẵng",
    "start_time": "15:30",
    "end_time": "17:00",
    "duration_minutes": 90,
    "cost_estimate": 70000,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "22 km (38 phút di chuyển)",
    "reason": "Trải nghiệm cảm giác lướt gió tốc độ cao xuyên rừng bằng xe trượt máng mạo hiểm hấp dẫn.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sun+World+Ba+Na+Hills"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Chiều",
    "stop_order": 8,
    "location_name": "Di chuyển về trung tâm thành phố",
    "category": "Di chuyển",
    "address": "35 Đỗ Thúc Tịnh, Cẩm Lệ, Đà Nẵng",
    "start_time": "17:00",
    "end_time": "18:00",
    "duration_minutes": 60,
    "cost_estimate": 150000,
    "rating": 4.5,
    "tiktok_popularity": "Trung bình",
    "distance_to_next": "0 km (tại điểm ăn tối)",
    "reason": "Xuống cáp treo và đón xe di chuyển về trung tâm thành phố ăn tối đặc sản.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bánh+tráng+thịt+heo+Quán+Mậu+Đà+Nẵng"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Tối",
    "stop_order": 9,
    "location_name": "Bánh tráng cuốn thịt heo Quán Mậu",
    "category": "Ăn uống",
    "address": "35 Đỗ Thúc Tịnh, Khuê Trung, Cẩm Lệ, Đà Nẵng",
    "start_time": "18:00",
    "end_time": "19:30",
    "duration_minutes": 90,
    "cost_estimate": 80000,
    "rating": 4.5,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "6 km (12 phút di chuyển)",
    "reason": "Món bánh tráng cuốn thịt heo hai đầu da chuẩn vị kèm mắm nêm bí truyền sánh đặc nồng nàn.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bánh+tráng+thịt+heo+Quán+Mậu+Đà+Nẵng"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Tối",
    "stop_order": 10,
    "location_name": "Chè Liên Hoàng Diệu",
    "category": "Ăn uống",
    "address": "189 Hoàng Diệu, Hải Châu, Đà Nẵng",
    "start_time": "19:30",
    "end_time": "20:30",
    "duration_minutes": 60,
    "cost_estimate": 30000,
    "rating": 4.5,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "2.5 km (6 phút di chuyển)",
    "reason": "Thưởng thức món chè sầu Liên béo ngậy nước cốt dừa nức tiếng gần xa làm món tráng miệng ngọt ngào.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Chè+Liên+Hoàng+Diệu+Đà+Nẵng"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Tối",
    "stop_order": 11,
    "location_name": "Chợ đêm Helio",
    "category": "Vui chơi",
    "address": "Đường 2 tháng 9, Hòa Cường Bắc, Hải Châu, Đà Nẵng",
    "start_time": "20:30",
    "end_time": "22:00",
    "duration_minutes": 90,
    "cost_estimate": 50000,
    "rating": 4.5,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "0.5 km (2 phút đi bộ)",
    "reason": "Hòa mình vào thiên đường ẩm thực đường phố sôi động và thưởng thức các buổi nhạc live acoustic ngoài trời cực vui.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Chợ+đêm+Helio"
  },
  {
    "date": "26/06/2026",
    "time_slot": "Tối",
    "stop_order": 12,
    "location_name": "Vòng quay mặt trời Sun Wheel (Asia Park)",
    "category": "Vui chơi",
    "address": "1 Phan Đăng Lưu, Hòa Cường Bắc, Hải Châu, Đà Nẵng",
    "start_time": "22:00",
    "end_time": "23:00",
    "duration_minutes": 60,
    "cost_estimate": 100000,
    "rating": 4.5,
    "tiktok_popularity": "Cao",
    "distance_to_next": "3 km (8 phút về khách sạn)",
    "reason": "Trải nghiệm vòng quay khổng lồ ngắm nhìn toàn bộ thành phố Đà Nẵng lung linh huyền ảo về đêm từ độ cao 115m.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Công+viên+Châu+Á"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Sáng",
    "stop_order": 1,
    "location_name": "Bán đảo Sơn Trà & Đỉnh Bàn Cờ (Ngắm bình minh)",
    "category": "Check-in",
    "address": "Thọ Quang, Sơn Trà, Đà Nẵng",
    "start_time": "06:00",
    "end_time": "07:00",
    "duration_minutes": 60,
    "cost_estimate": 0,
    "rating": 4.6,
    "tiktok_popularity": "Cao",
    "distance_to_next": "9.5 km (16 phút di chuyển)",
    "reason": "Đón những tia nắng bình minh đầu tiên của ngày mới tại đỉnh núi cao nhất Sơn Trà gắn liền truyền thuyết Đế Thích.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Đỉnh+Bàn+Cờ"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Sáng",
    "stop_order": 2,
    "location_name": "Bún chả cá Hờn",
    "category": "Ăn uống",
    "address": "139/5 Hùng Vương, Hải Châu 2, Hải Châu, Đà Nẵng",
    "start_time": "07:00",
    "end_time": "08:00",
    "duration_minutes": 60,
    "cost_estimate": 35000,
    "rating": 4.5,
    "tiktok_popularity": "Cao",
    "distance_to_next": "0.6 km (2 phút di chuyển)",
    "reason": "Thưởng thức bát bún cá thu dai ngọt thơm ngon với giá cả bình dân được giới học sinh sinh viên rất mê.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bún+chả+cá+Hờn+Đà+Nẵng"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Sáng",
    "stop_order": 3,
    "location_name": "Ikigai Garden Cafe",
    "category": "Cafe",
    "address": "60 Nguyễn Chí Thanh, Hải Châu 1, Hải Châu, Đà Nẵng",
    "start_time": "08:00",
    "end_time": "09:30",
    "duration_minutes": 90,
    "cost_estimate": 40000,
    "rating": 4.5,
    "tiktok_popularity": "Cao",
    "distance_to_next": "9.5 km (16 phút di chuyển)",
    "reason": "Quán cafe phong cách sân vườn Nhật Bản tinh tế, không gian gỗ thanh bình thưởng thức trà matcha rất ngon.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Ikigai+Garden+Cafe+Nguyễn+Chí+Thanh"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Sáng",
    "stop_order": 4,
    "location_name": "Chùa Linh Ứng Bãi Bụt",
    "category": "Du lịch",
    "address": "Bán đảo Sơn Trà, Thọ Quang, Sơn Trà, Đà Nẵng",
    "start_time": "09:30",
    "end_time": "11:30",
    "duration_minutes": 120,
    "cost_estimate": 0,
    "rating": 4.8,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "6.5 km (12 phút di chuyển)",
    "reason": "Chiêm bái tượng Phật Quan Thế Âm cao nhất Việt Nam (67m) hướng ra biển xanh mênh mông cầu bình an.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Chùa+Linh+Ứng+Sơn+Trà"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Trưa",
    "stop_order": 5,
    "location_name": "Hải sản Năm Đảnh",
    "category": "Ăn uống",
    "address": "K139/H59/38 Trần Quang Khải, Thọ Quang, Sơn Trà, Đà Nẵng",
    "start_time": "11:30",
    "end_time": "13:00",
    "duration_minutes": 90,
    "cost_estimate": 150000,
    "rating": 4.5,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "7 km (14 phút di chuyển)",
    "reason": "Quán hải sản hẻm siêu hot TikTok nức tiếng Đà Nẵng về độ tươi ngon, đa dạng món ăn và giá cực kỳ rẻ.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Năm+Đảnh"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Trưa",
    "stop_order": 6,
    "location_name": "Boulevard Gelato & Coffee",
    "category": "Cafe",
    "address": "77 Trần Quốc Toản, Hải Châu 1, Hải Châu, Đà Nẵng",
    "start_time": "13:00",
    "end_time": "14:00",
    "duration_minutes": 60,
    "cost_estimate": 50000,
    "rating": 4.5,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "0.8 km (3 phút di chuyển)",
    "reason": "Quán kem và cafe mang vibe châu Âu lãng mạn, các vị kem gelato ngọt dịu mịn màng giải nhiệt ngày hè cực đỉnh.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Boulevard+Gelato+Coffee+Đà+Nẵng"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Chiều",
    "stop_order": 7,
    "location_name": "Công viên APEC",
    "category": "Check-in",
    "address": "Đường 2 Tháng 9, Bình Hiên, Hải Châu, Đà Nẵng",
    "start_time": "14:00",
    "end_time": "16:00",
    "duration_minutes": 120,
    "cost_estimate": 0,
    "rating": 4.5,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "3.5 km (8 phút di chuyển)",
    "reason": "Check-in mái vòm thiết kế hình cánh diều khổng lồ bay cao biểu tượng mới đầy khát vọng của thành phố biển.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Công+viên+APEC+Đà+Nẵng"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Chiều",
    "stop_order": 8,
    "location_name": "Lễ hội biển Đà Nẵng 2026 (An Hải Festival)",
    "category": "Sự kiện",
    "address": "Công viên Biển Đông, Võ Nguyên Giáp, Phước Mỹ, Sơn Trà, Đà Nẵng",
    "start_time": "16:00",
    "end_time": "18:00",
    "duration_minutes": 120,
    "cost_estimate": 0,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "4.2 km (9 phút di chuyển)",
    "reason": "Sự kiện hè đặc sắc, trải nghiệm các gian hàng sản phẩm OCOP địa phương và nghe trình diễn âm nhạc bãi biển.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Công+viên+Biển+Đông+Đà+Nẵng"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Tối",
    "stop_order": 9,
    "location_name": "Bún mắm nêm Bé Hà",
    "category": "Ăn uống",
    "address": "130 Hùng Vương, Hải Châu 1, Hải Châu, Đà Nẵng",
    "start_time": "18:00",
    "end_time": "19:30",
    "duration_minutes": 90,
    "cost_estimate": 40000,
    "rating": 4.5,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "1.8 km (5 phút di chuyển)",
    "reason": "Ăn tối nhanh với bát bún mắm nêm đậm đà kết hợp thịt heo quay da giòn rụm và mít non hấp dẫn.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bún+mắm+nêm+Bé+Hà+Đà+Nẵng"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Tối",
    "stop_order": 10,
    "location_name": "Lễ hội Pháo hoa Quốc tế Đà Nẵng (DIFF) 2026 - Đêm 5",
    "category": "Sự kiện",
    "address": "Cảng Sông Hàn, vỉa hè Trần Hưng Đạo, Sơn Trà, Đà Nẵng",
    "start_time": "19:30",
    "end_time": "22:00",
    "duration_minutes": 150,
    "cost_estimate": 500000,
    "rating": 4.8,
    "tiktok_popularity": "Cực cao",
    "distance_to_next": "1 km (3 phút di chuyển)",
    "reason": "Tâm điểm sự kiện du lịch hè với màn tranh tài pháo hoa đỉnh cao của hai đội Úc và Bồ Đào Nha rực sáng sông Hàn.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Bến+du+thuyền+Sông+Hàn"
  },
  {
    "date": "27/06/2026",
    "time_slot": "Tối",
    "stop_order": 11,
    "location_name": "Cầu Rồng Phun Lửa / Nước",
    "category": "Du lịch",
    "address": "Đường Nguyễn Văn Linh, Phước Ninh, Hải Châu, Đà Nẵng",
    "start_time": "22:00",
    "end_time": "23:00",
    "duration_minutes": 60,
    "cost_estimate": 0,
    "rating": 4.7,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "1.5 km (4 phút về khách sạn)",
    "reason": "Chiêm ngưỡng màn trình diễn phun lửa & nước độc đáo cuối tuần của biểu tượng thành phố sông Hàn.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Cầu+Rồng+Đà+Nẵng"
  },
  {
    "date": "28/06/2026",
    "time_slot": "Sáng",
    "stop_order": 1,
    "location_name": "Đèo Hải Vân & Check-in Cây Cô Đơn, Tiệm cafe hòn đá",
    "category": "Check-in",
    "address": "Đường đèo Hải Vân, Liên Chiểu, Đà Nẵng",
    "start_time": "06:00",
    "end_time": "08:30",
    "duration_minutes": 150,
    "cost_estimate": 30000,
    "rating": 4.7,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "28 km (45 phút di chuyển)",
    "reason": "Chinh phục 'Thiên hạ đệ nhất hùng quan' ngắm vịnh biển Đà Nẵng tuyệt sắc sương phủ và uống cafe sớm.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Đèo+Hải+Vân"
  },
  {
    "date": "28/06/2026",
    "time_slot": "Sáng",
    "stop_order": 2,
    "location_name": "Cơm gà A Hải",
    "category": "Ăn uống",
    "address": "96 Phan Châu Trinh, Phước Ninh, Hải Châu, Đà Nẵng",
    "start_time": "08:30",
    "end_time": "09:30",
    "duration_minutes": 60,
    "cost_estimate": 60000,
    "rating": 4.5,
    "tiktok_popularity": "Cao",
    "distance_to_next": "1.2 km (4 phút di chuyển)",
    "reason": "Ăn sáng muộn / trưa sớm bằng đĩa cơm gà quay giòn tan, ngọt thịt trứ danh bậc nhất Đà thành.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Cơm+gà+A+Hải+Đà+Nẵng"
  },
  {
    "date": "28/06/2026",
    "time_slot": "Sáng",
    "stop_order": 3,
    "location_name": "Chợ Cồn Đà Nẵng (Mua sắm & Tham quan)",
    "category": "Vui chơi",
    "address": "290 Hùng Vương, Vĩnh Trung, Hải Châu, Đà Nẵng",
    "start_time": "09:30",
    "end_time": "11:00",
    "duration_minutes": 90,
    "cost_estimate": 50000,
    "rating": 4.5,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "0 km (tại chỗ)",
    "reason": "Khám phá ngôi chợ truyền thống sầm uất bậc nhất, tham quan các gian hàng đặc sản làm quà lưu niệm.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Chợ+Cồn+Đà+Nẵng"
  },
  {
    "date": "28/06/2026",
    "time_slot": "Trưa",
    "stop_order": 4,
    "location_name": "Food tour Chợ Cồn (Ăn trưa)",
    "category": "Ăn uống",
    "address": "Khu ẩm thực Chợ Cồn, Hải Châu, Đà Nẵng",
    "start_time": "11:00",
    "end_time": "12:30",
    "duration_minutes": 90,
    "cost_estimate": 80000,
    "rating": 4.5,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "2.5 km (7 phút di chuyển)",
    "reason": "Càn quét thiên đường ăn vặt với bún lòng nghệ Cô Cúc, bánh bèo, bánh lọc, ram cuốn lá cải ngon quên sầu.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Chợ+Cồn+Đà+Nẵng"
  },
  {
    "date": "28/06/2026",
    "time_slot": "Trưa",
    "stop_order": 5,
    "location_name": "Ibasho Coffee & Hostel",
    "category": "Cafe",
    "address": "124-126 Yên Khê 1, Hòa Minh, Thanh Khê, Đà Nẵng",
    "start_time": "12:30",
    "end_time": "14:00",
    "duration_minutes": 90,
    "cost_estimate": 45000,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "4.5 km (10 phút di chuyển)",
    "reason": "Quán cafe phong cách tối giản Nhật Bản ngập tràn ánh nắng tự nhiên, góc check-in tinh tế và rất mát mẻ.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Ibasho+Coffee+Đà+Nẵng"
  },
  {
    "date": "28/06/2026",
    "time_slot": "Chiều",
    "stop_order": 6,
    "location_name": "Check-in Cầu Nguyễn Văn Trỗi",
    "category": "Check-in",
    "address": "Cầu Nguyễn Văn Trỗi, Hải Châu, Đà Nẵng",
    "start_time": "14:00",
    "end_time": "15:30",
    "duration_minutes": 90,
    "cost_estimate": 0,
    "rating": 4.5,
    "tiktok_popularity": "Cao",
    "distance_to_next": "11 km (20 phút di chuyển)",
    "reason": "Dạo bước trên cây cầu dã chiến bằng giàn thép vàng lịch sử đầy cổ kính và ngắm hoàng hôn sông Hàn.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Cầu+Nguyễn+Văn+Trỗi"
  },
  {
    "date": "28/06/2026",
    "time_slot": "Chiều",
    "stop_order": 7,
    "location_name": "Nami Beach Club (Mikazuki Resort)",
    "category": "Cafe",
    "address": "Đường Nguyễn Tất Thành, Hòa Hiệp Nam, Liên Chiểu, Đà Nẵng",
    "start_time": "15:30",
    "end_time": "17:00",
    "duration_minutes": 90,
    "cost_estimate": 100000,
    "rating": 4.6,
    "tiktok_popularity": "Rất cao",
    "distance_to_next": "9 km (16 phút di chuyển)",
    "reason": "Ngắm hoàng hôn vịnh biển siêu lãng mạn sát biển, phong cách nhiệt đới cực kỳ sang chảnh nổi rần rần trên TikTok.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Nami+Beach+Club+Mikazuki"
  },
  {
    "date": "28/06/2026",
    "time_slot": "Chiều",
    "stop_order": 8,
    "location_name": "Chuẩn bị hành lý & di chuyển ra sân bay",
    "category": "Di chuyển",
    "address": "Sân bay Quốc tế Đà Nẵng, Hải Châu, Đà Nẵng",
    "start_time": "17:00",
    "end_time": "18:00",
    "duration_minutes": 60,
    "cost_estimate": 100000,
    "rating": 4.4,
    "tiktok_popularity": "Trung bình",
    "distance_to_next": "0 km (kết thúc)",
    "reason": "Mua sắm nốt các đặc sản làm quà, làm thủ tục gửi hành lý và kiểm tra an ninh tại sân bay.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sân+bay+Quốc+tế+Đà+Nẵng"
  },
  {
    "date": "28/06/2026",
    "time_slot": "Tối",
    "stop_order": 9,
    "location_name": "Bay về nhà, kết thúc hành trình",
    "category": "Di chuyển",
    "address": "Sân bay Quốc tế Đà Nẵng",
    "start_time": "18:00",
    "end_time": "21:00",
    "duration_minutes": 180,
    "cost_estimate": 0,
    "rating": 4.4,
    "tiktok_popularity": "Trung bình",
    "distance_to_next": "0 km",
    "reason": "Bay trở về nhà, kết thúc trọn vẹn chuyến du lịch khám phá Đà Nẵng 4 ngày 3 đêm.",
    "google_maps_url": "https://www.google.com/maps/search/?api=1&query=Sân+bay+Quốc+tế+Đà+Nẵng"
  }
];

const RECOMMENDATIONS = [
  {
    "name": "Mì Quảng Bà Mua",
    "category": "Ăn uống",
    "address": "19-21 Trần Bình Trọng, Hải Châu, Đà Nẵng",
    "price_range": "40k - 60k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Mì Quảng hương vị truyền thống đậm đà, thương hiệu lâu đời, được đông đảo du khách đánh giá cao.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Mì+Quảng+Bà+Mua+Trần+Bình+Trọng"
  },
  {
    "name": "Bún chả cá Hờn",
    "category": "Ăn uống",
    "address": "139/5 Hùng Vương, Hải Châu, Đà Nẵng",
    "price_range": "30k - 45k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Bún chả cá ngon trứ danh, nước dùng thanh ngọt, chả cá dai ngọt tự làm, giá vô cùng học sinh sinh viên.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bún+chả+cá+Hờn+Đà+Nẵng"
  },
  {
    "name": "Bún mắm nêm Bé Hà",
    "category": "Ăn uống",
    "address": "130 Hùng Vương, Hải Châu, Đà Nẵng",
    "price_range": "30k - 50k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Bún mắm nêm thơm nức mũi ăn kèm thịt heo quay da giòn rụm và mít non luộc ngọt mát chuẩn vị Đà Nẵng.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bún+mắm+nêm+Bé+Hà+Đà+Nẵng"
  },
  {
    "name": "Bánh tráng cuốn thịt heo Quán Mậu",
    "category": "Ăn uống",
    "address": "35 Đỗ Thúc Tịnh, Cẩm Lệ, Đà Nẵng",
    "price_range": "60k - 100k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Bánh tráng cuốn thịt heo hai đầu da luộc vừa chín tới, ăn kèm mắm nêm bí truyền sánh đặc ngon quên sầu.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bánh+tráng+thịt+heo+Quán+Mậu+Đà+Nẵng"
  },
  {
    "name": "Bánh tráng thịt heo Đại Lộc",
    "category": "Ăn uống",
    "address": "97 Trưng Nữ Vương, Hải Châu, Đà Nẵng",
    "price_range": "40k - 70k VND",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Bánh tráng phơi sương Đại Lộc dai mềm, thịt heo quê thơm ngon, rau sống đủ loại, giá cả phải chăng.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bánh+tráng+thịt+heo+Đại+Lộc+Đà+Nẵng"
  },
  {
    "name": "Bún chả cá Ông Tạ",
    "category": "Ăn uống",
    "address": "113A Nguyễn Chí Thanh, Hải Châu, Đà Nẵng",
    "price_range": "35k - 60k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Nước lèo ngọt thanh từ rau củ kết hợp chả cá thu chiên/hấp tươi rói đem đến hương vị đậm đà khó quên.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bún+chả+cá+Ông+Tạ+Đà+Nẵng"
  },
  {
    "name": "Bánh xèo Bà Dưỡng",
    "category": "Ăn uống",
    "address": "K280/23 Hoàng Diệu, Hải Châu, Đà Nẵng",
    "price_range": "50k - 100k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Quán bánh xèo nem lụi siêu hot hit trên TikTok với lớp vỏ bánh giòn rụm màu vàng nghệ và nước chấm gan béo ngậy.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bánh+xèo+Bà+Dưỡng+Đà+Nẵng"
  },
  {
    "name": "Mì Quảng Cô Sáu",
    "category": "Ăn uống",
    "address": "397 Trần Hưng Đạo, Sơn Trà, Đà Nẵng",
    "price_range": "25k - 40k VND",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Quán ăn bình dân sát sông Hàn phục vụ mì Quảng tôm thịt đậm vị địa phương với giá siêu mềm.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Mì+Quảng+Cô+Sáu+Trần+Hưng+Đạo"
  },
  {
    "name": "Bún thịt nướng cô Xuân",
    "category": "Ăn uống",
    "address": "491 Hải Phòng, Thanh Khê, Đà Nẵng",
    "price_range": "30k - 45k VND",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Thịt nướng thơm lừng đậm đà ăn kèm ram giòn và nước tương đậu phộng đặc sánh thơm ngậy.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bún+thịt+nướng+cô+Xuân+Hải+Phòng"
  },
  {
    "name": "Kem bơ Cô Vân Chợ Bắc Mỹ An",
    "category": "Ăn uống",
    "address": "Chợ Bắc Mỹ An, Mỹ An, Ngũ Hành Sơn, Đà Nẵng",
    "price_range": "15k - 25k VND",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Ly kem bơ dừa ngọt ngào béo ngậy được review điên đảo trên TikTok, giá hạt dẻ thích hợp giải nhiệt mùa hè.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Chợ+Bắc+Mỹ+An"
  },
  {
    "name": "Bánh tráng kẹp Dì Hoa",
    "category": "Ăn uống",
    "address": "K96/130 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
    "price_range": "15k - 30k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Điểm ăn vặt quen thuộc của học sinh sinh viên với bánh tráng bò khô ướt, bánh tráng pate trứng nướng giòn rụm.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bánh+tráng+kẹp+Dì+Hoa"
  },
  {
    "name": "Bún lòng nghệ Cô Cúc Chợ Cồn",
    "category": "Ăn uống",
    "address": "Chợ Cồn, Ông Ích Khiêm, Hải Châu, Đà Nẵng",
    "price_range": "25k - 40k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Món bún lòng xào nghệ vàng tươi bắt mắt, thơm mùi nén và nghệ, lòng dai sần sật lạ miệng rất đặc trưng.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Chợ+Cồn+Đà+Nẵng"
  },
  {
    "name": "Bún bò Huế Mệ Mui",
    "category": "Ăn uống",
    "address": "63 Lê Hồng Phong, Hải Châu, Đà Nẵng",
    "price_range": "40k - 65k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Hương vị bún bò chuẩn Huế lâu đời tại Đà Nẵng với nước dùng thơm mùi sả mắm ruốc đặc trưng.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bún+bò+Huế+Mệ+Mui"
  },
  {
    "name": "Cơm gà A Hải",
    "category": "Ăn uống",
    "address": "96 Phan Châu Trinh, Hải Châu, Đà Nẵng",
    "price_range": "50k - 75k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Cơm gà quay giòn tan, thịt gà ngọt dai kèm chén nước sốt đậm đà, là quán cơm gà đông khách nhất nhì Đà thành.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cơm+gà+A+Hải+Đà+Nẵng"
  },
  {
    "name": "Bánh căn bánh đập Cô Đỗ",
    "category": "Ăn uống",
    "address": "47 Tô Hiến Thành, Sơn Trà, Đà Nẵng",
    "price_range": "20k - 40k VND",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Bánh đập giòn rụm chấm mắm nêm đậm vị và bánh căn trứng cút thơm bùi ăn hoài không ngán.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bánh+căn+bánh+đập+Tô+Hiến+Thành"
  },
  {
    "name": "Chè Liên Hoàng Diệu",
    "category": "Ăn uống",
    "address": "189 Hoàng Diệu, Hải Châu, Đà Nẵng",
    "price_range": "20k - 35k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Món chè sầu Liên béo ngậy nước cốt dừa, thơm nức sầu riêng tươi đã trở thành thương hiệu ẩm thực quốc dân Đà Nẵng.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Chè+Liên+Hoàng+Diệu+Đà+Nẵng"
  },
  {
    "name": "Bánh mì Bà Lan",
    "category": "Ăn uống",
    "address": "62 Trưng Nữ Vương, Hải Châu, Đà Nẵng",
    "price_range": "20k - 35k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Bánh mì patê thơm phức dày cùi, chả bò Đà Nẵng ngọt dai cắt lát dày, vỏ bánh mì nướng giòn rụm.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bánh+mì+Bà+Lan+Trưng+Nữ+Vương"
  },
  {
    "name": "Bún riêu cua Bà Đào",
    "category": "Ăn uống",
    "address": "10 Pasteur, Hải Châu, Đà Nẵng",
    "price_range": "30k - 45k VND",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Bún riêu cua đồng chuẩn vị ngọt đậm đà, riêu cua nhiều gạch chưng béo ngậy kèm rau sống xắt nhỏ thanh mát.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bún+riêu+cua+Bà+Đào+Pasteur"
  },
  {
    "name": "Ram cuốn lá cải Việt",
    "category": "Ăn uống",
    "address": "Khu vực Chợ Cồn, Hải Châu, Đà Nẵng",
    "price_range": "25k - 40k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Ram chiên giòn rụm nóng hổi cuốn cùng bánh tráng, lá cải đắng đuôi, chấm nước mắm chua ngọt cực hấp dẫn.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Chợ+Cồn+Đà+Nẵng"
  },
  {
    "name": "Bún chả cá Nguyễn Chí Thanh",
    "category": "Ăn uống",
    "address": "109 Nguyễn Chí Thanh, Hải Châu, Đà Nẵng",
    "price_range": "35k - 55k VND",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Thêm một địa chỉ bún chả cá lâu đời có nước dùng hầm từ xương cá ngọt đậm đà, chả cá dai ngọt tự nhiên.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bún+chả+cá+Nguyễn+Chí+Thanh"
  },
  {
    "name": "Hải sản Năm Đảnh",
    "category": "Ăn uống",
    "address": "K139/H59/38 Trần Quang Khải, Sơn Trà, Đà Nẵng",
    "price_range": "60k - 150k VND / món",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Quán hải sản hẻm siêu nổi tiếng trên TikTok với phương châm ngon bổ rẻ, các món ốc, ghẹ, mực đồng giá cực tốt.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Năm+Đảnh"
  },
  {
    "name": "Hải sản Mộc Quán",
    "category": "Ăn uống",
    "address": "26 Tô Hiến Thành, Sơn Trà, Đà Nẵng",
    "price_range": "80k - 250k VND / món",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Không gian quán decor mộc mạc, chụp ảnh đẹp. Đồ ăn chế biến đa dạng hương vị đậm đà và hải sản cực kỳ tươi.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Mộc+Quán+Đà+Nẵng"
  },
  {
    "name": "Hải sản Bé Mặn",
    "category": "Ăn uống",
    "address": "Lô 8 Võ Nguyên Giáp, Sơn Trà, Đà Nẵng",
    "price_range": "150k - 400k VND / món",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Nằm ngay ven biển Mỹ Khê lộng gió, nổi tiếng với hải sản tươi sống bắt tại bể, chế biến chuyên nghiệp.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Bé+Mặn+Võ+Nguyên+Giáp"
  },
  {
    "name": "Hải sản Thời Cổ",
    "category": "Ăn uống",
    "address": "354/1 Võ Nguyên Giáp, Ngũ Hành Sơn, Đà Nẵng",
    "price_range": "70k - 200k VND / món",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Quán hải sản bình dân ven biển rất phù hợp cho sinh viên với nhiều combo tôm hùm, cua sốt trứng muối giá hời.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Thời+Cổ+Võ+Nguyên+Giáp"
  },
  {
    "name": "Hải sản Bà Rô",
    "category": "Ăn uống",
    "address": "115 Lý Tử Tấn, Sơn Trà, Đà Nẵng",
    "price_range": "60k - 150k VND / món",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Quán hải sản địa phương nằm xa trung tâm một chút nhưng giá siêu mềm, đồ ăn ra nhanh nóng hổi chất lượng.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Bà+Rô+Lý+Tử+Tấn"
  },
  {
    "name": "Hải sản Phố",
    "category": "Ăn uống",
    "address": "51 Võ Nguyên Giáp, Ngũ Hành Sơn, Đà Nẵng",
    "price_range": "150k - 500k VND / món",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Không gian nhà hàng sang trọng đẳng cấp ngắm trực diện biển Mỹ Khê, dịch vụ xuất sắc thích hợp tiếp khách/gia đình.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Phố+Võ+Nguyên+Giáp"
  },
  {
    "name": "Hải sản Kỳ Em",
    "category": "Ăn uống",
    "address": "179 Hồ Nghinh, Sơn Trà, Đà Nẵng",
    "price_range": "100k - 300k VND / món",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Điểm ăn hải sản quen thuộc lâu năm của người dân Đà thành, nổi tiếng với lẩu hải sản và ghẹ hấp ngọt thịt.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Kỳ+Em+Hồ+Nghinh"
  },
  {
    "name": "Hải sản Lão Đại",
    "category": "Ăn uống",
    "address": "Lô 1 Võ Văn Kiệt, Sơn Trà, Đà Nẵng",
    "price_range": "70k - 200k VND / món",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Không gian quán nhậu vỉa hè rộng rãi thoáng mát trên đại lộ Võ Văn Kiệt, các món ốc hương trứng muối rất cuốn.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Lão+Đại+Võ+Văn+Kiệt"
  },
  {
    "name": "Hải sản Bé Anh",
    "category": "Ăn uống",
    "address": "Lô B14-15 Hồ Nghinh, Sơn Trà, Đà Nẵng",
    "price_range": "150k - 400k VND / món",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Nhà hàng hải sản uy tín, đồ ăn tươi ngon nêm nếm vừa vặn, không gian thoáng đãng sạch sẽ.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Bé+Anh+Hồ+Nghinh"
  },
  {
    "name": "Hải sản Eo Biển",
    "category": "Ăn uống",
    "address": "189 Nguyễn Phan Vinh, Sơn Trà, Đà Nẵng",
    "price_range": "60k - 180k VND / món",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Hải sản tươi rói mua trực tiếp từ thuyền chài Thọ Quang mang lên chế biến luôn nên độ ngọt tự nhiên rất cao.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hải+sản+Eo+Biển+Nguyễn+Phan+Vinh"
  },
  {
    "name": "Trình Cà Phê",
    "category": "Cafe",
    "address": "34/4 Nguyễn Hữu Thọ, Hải Châu, Đà Nẵng",
    "price_range": "25k - 45k VND",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Phong cách quán vườn cổ điển, nhiều mảng xanh, cực kỳ chill và hoài niệm, trà trái cây rất ngon.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Trình+Cà+Phê+Nguyễn+Hữu+Thọ+Đà+Nẵng"
  },
  {
    "name": "Namto House Coffee",
    "category": "Cafe",
    "address": "130 Nguyễn Chí Thanh, Hải Châu, Đà Nẵng",
    "price_range": "30k - 55k VND",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Thiết kế tông màu nâu gỗ ấm cúng kiểu Hàn Quốc tinh tế, góc nào cũng ngập tràn ánh sáng sống ảo xuất sắc.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Namto+House+Coffee+130+Nguyễn+Chí+Thanh"
  },
  {
    "name": "Reply 1988 Cafe",
    "category": "Cafe",
    "address": "20 Lê Hồng Phong, Hải Châu, Đà Nẵng",
    "price_range": "35k - 60k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Vibe retro Hàn Quốc thời thượng với thiết kế tối giản sang trọng, đồ uống decor xinh xắn hot rầm rộ TikTok.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Reply+1988+Cafe+Đà+Nẵng"
  },
  {
    "name": "Ibasho Coffee & Hostel",
    "category": "Cafe",
    "address": "124-126 Yên Khê 1, Thanh Khê, Đà Nẵng",
    "price_range": "35k - 55k VND",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Phong cách Nhật Bản tối giản tone trắng sáng ngập tràn ánh nắng tự nhiên, có sân vườn chụp ảnh OOTD siêu đẹp.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ibasho+Coffee+Đà+Nẵng"
  },
  {
    "name": "Boulevard Gelato & Coffee",
    "category": "Cafe",
    "address": "77 Trần Quốc Toản, Hải Châu, Đà Nẵng",
    "price_range": "35k - 65k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Không gian châu Âu lãng mạn sang trọng, nổi tiếng với các vị kem gelato Ý béo mịn tự nhiên và bánh ngọt ngon mắt.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Boulevard+Gelato+Coffee+Đà+Nẵng"
  },
  {
    "name": "Út Tịch Cafe",
    "category": "Cafe",
    "address": "71 Bạch Đằng, Hải Châu, Đà Nẵng",
    "price_range": "30k - 50k VND",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Quán cafe đậm chất xưa cũ Việt Nam ngay mặt tiền Bạch Đằng ngắm sông Hàn mát rượi, nước uống ngon vị truyền thống.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Út+Tịch+Cafe+Bạch+Đằng+Đà+Nẵng"
  },
  {
    "name": "Ikigai Garden Cafe",
    "category": "Cafe",
    "address": "60 Nguyễn Chí Thanh, Hải Châu, Đà Nẵng",
    "price_range": "30k - 55k VND",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Không gian gỗ mộc mạc phong cách sân vườn Nhật Bản mang nét thanh tịnh nhẹ nhàng, thức uống vị matcha cực chuẩn.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ikigai+Garden+Cafe+Nguyễn+Chí+Thanh"
  },
  {
    "name": "Wonderlust Cafe & Bakery",
    "category": "Cafe",
    "address": "96 Trần Phú, Hải Châu, Đà Nẵng",
    "price_range": "40k - 70k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Tổ hợp cafe bánh ngọt & shop thời trang tone trắng đen thời thượng dưới mái kính ngập nắng check-in sang chảnh.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Wonderlust+Cafe+Bakery+Đà+Nẵng"
  },
  {
    "name": "Dreamer Coffee",
    "category": "Cafe",
    "address": "230/2 Nguyễn Công Trứ, Sơn Trà, Đà Nẵng",
    "price_range": "35k - 60k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Khu vườn cổ tích lung linh ánh đèn buổi tối, thường xuyên tổ chức các đêm nhạc acoustic nhẹ nhàng lãng mạn cho cặp đôi.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Dreamer+Coffee+Nguyễn+Công+Trứ"
  },
  {
    "name": "Nami Beach Club",
    "category": "Cafe",
    "address": "Mikazuki Resort, Nguyễn Tất Thành, Liên Chiểu, Đà Nẵng",
    "price_range": "80k - 200k VND",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Tọa độ ngắm hoàng hôn vịnh Đà Nẵng siêu chill sát biển, phong cách nhiệt đới cực kỳ sang xịn mịn nổi rần rần trên TikTok.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Nami+Beach+Club+Mikazuki"
  },
  {
    "name": "Cầu Vàng (Sun World Ba Na Hills)",
    "category": "Check-in",
    "address": "Núi Chúa, Hòa Ninh, Hòa Vang, Đà Nẵng",
    "price_range": "950k VND (Vé cáp treo)",
    "rating": 4.7,
    "tiktok_hot": true,
    "reason": "Kỳ quan kiến trúc đẳng cấp thế giới được nâng đỡ bởi hai bàn tay rêu phong cổ kính giữa núi ngàn sương phủ.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sun+World+Ba+Na+Hills"
  },
  {
    "name": "Chùa Linh Ứng Bãi Bụt",
    "category": "Check-in",
    "address": "Bán đảo Sơn Trà, Thọ Quang, Sơn Trà, Đà Nẵng",
    "price_range": "Miễn phí (Gửi xe tùy tâm)",
    "rating": 4.8,
    "tiktok_hot": true,
    "reason": "Điểm du lịch tâm linh nổi tiếng, sở hữu phong cảnh hữu tình ngắm toàn cảnh thành phố biển và tượng Phật khổng lồ.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Chùa+Linh+Ứng+Sơn+Trà"
  },
  {
    "name": "Biển Mỹ Khê",
    "category": "Check-in",
    "address": "Đường Võ Nguyên Giáp, Sơn Trà, Đà Nẵng",
    "price_range": "Miễn phí",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Bãi biển sạch đẹp sóng êm, cát mịn nằm trong top đẹp nhất thế giới, là nơi ngắm bình minh tuyệt vời nhất thành phố.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Biển+Mỹ+Khê+Đà+Nẵng"
  },
  {
    "name": "Công viên APEC",
    "category": "Check-in",
    "address": "Đường 2 tháng 9, Bình Hiên, Hải Châu, Đà Nẵng",
    "price_range": "Miễn phí",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Kiến trúc mái vòm cánh diều uốn lượn bằng thép khổng lồ cực chất, biểu tượng mới cho khát vọng bay cao của Đà thành.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Công+viên+APEC+Đà+Nẵng"
  },
  {
    "name": "Cầu Tình Yêu & Tượng Cá Chép Hóa Rồng",
    "category": "Check-in",
    "address": "Đường Trần Hưng Đạo, Sơn Trà, Đà Nẵng",
    "price_range": "Miễn phí",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Cây cầu treo lãng mạn gắn những ổ khóa tình yêu của các cặp đôi cùng tượng Cá chép hóa rồng phun nước tuyệt đẹp bên sông Hàn.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cầu+Tình+Yêu+Đà+Nẵng"
  },
  {
    "name": "Đèo Hải Vân (Cây cô đơn & Tiệm cafe hòn đá)",
    "category": "Check-in",
    "address": "Đường đèo Hải Vân, Liên Chiểu, Đà Nẵng",
    "price_range": "Miễn phí (Nước uống cafe ~30k)",
    "rating": 4.7,
    "tiktok_hot": true,
    "reason": "Thiên hạ đệ nhất hùng quan với đèo uốn lượn ngắm trọn đại dương xanh thẳm, check-in cây cô đơn siêu lãng mạn.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Đèo+Hải+Vân"
  },
  {
    "name": "Nhà thờ Con Gà (Nhà thờ Chính Tòa)",
    "category": "Check-in",
    "address": "156 Trần Phú, Hải Châu, Đà Nẵng",
    "price_range": "Miễn phí",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Kiến trúc Gothic cổ kính màu hồng pastel duy nhất từ thời Pháp tại Đà Nẵng mang nét vintage châu Âu thơ mộng.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Nhà+thờ+Con+Gà+Đà+Nẵng"
  },
  {
    "name": "Cung Văn hóa Thiếu nhi Đà Nẵng",
    "category": "Check-in",
    "address": "2 Phan Đăng Lưu, Hải Châu, Đà Nẵng",
    "price_range": "Miễn phí",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Những khối tường trang trí hình học đa sắc màu xếp lớp ngộ nghĩnh (phong cách Tangram) lên hình cực cá tính.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cung+Văn+hóa+Thiếu+nhi+Đà+Nẵng"
  },
  {
    "name": "Đỉnh Bàn Cờ (Bán đảo Sơn Trà)",
    "category": "Check-in",
    "address": "Thọ Quang, Sơn Trà, Đà Nẵng",
    "price_range": "Miễn phí",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Đỉnh núi cao nhất Sơn Trà gắn với truyền thuyết Đế Thích chơi cờ, ngắm toàn cảnh mây trời Đà Nẵng tuyệt đẹp.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Đỉnh+Bàn+Cờ"
  },
  {
    "name": "Cầu Nguyễn Văn Trỗi",
    "category": "Check-in",
    "address": "Cầu Nguyễn Văn Trỗi, Hải Châu, Đà Nẵng",
    "price_range": "Miễn phí",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Cây cầu dã chiến lịch sử bằng giàn thép sơn vàng nghệ tuyệt đẹp dành riêng cho người đi bộ ngắm hoàng hôn yên ả.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cầu+Nguyễn+Văn+Trỗi"
  },
  {
    "name": "Cầu Rồng (Phun Lửa/Nước)",
    "category": "Vui chơi",
    "address": "Đường Nguyễn Văn Linh, Hải Châu, Đà Nẵng",
    "price_range": "Miễn phí",
    "rating": 4.7,
    "tiktok_hot": true,
    "reason": "Biểu tượng sống động nhất của thành phố với màn trình diễn độc đáo phun lửa và nước vào cuối tuần lúc 21:00.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cầu+Rồng+Đà+Nẵng"
  },
  {
    "name": "Chợ đêm Helio & Helio Center",
    "category": "Vui chơi",
    "address": "Đường 2 tháng 9, Hải Châu, Đà Nẵng",
    "price_range": "20k - 150k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Không gian vui chơi ăn uống sầm uất với bia ngon, ca nhạc live acoustic hàng đêm và hàng trăm gian hàng ẩm thực hấp dẫn.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Chợ+đêm+Helio"
  },
  {
    "name": "Du thuyền Sông Hàn",
    "category": "Vui chơi",
    "address": "Bến du thuyền Đà Nẵng, Bạch Đằng, Đà Nẵng",
    "price_range": "120k - 200k VND",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Trải nghiệm đi tàu lướt trên sông Hàn lộng gió ngắm toàn bộ 4 cây cầu ánh sáng lung linh rực rỡ nhất về đêm.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Bến+du+thuyền+Sông+Hàn"
  },
  {
    "name": "Chợ đêm Sơn Trà",
    "category": "Vui chơi",
    "address": "Đường Trần Hưng Đạo, Sơn Trà, Đà Nẵng",
    "price_range": "20k - 100k VND",
    "rating": 4.4,
    "tiktok_hot": true,
    "reason": "Nằm ngay chân Cầu Rồng rất nhộn nhịp, bán đầy đủ quà lưu niệm và hải sản nướng, đồ ăn vặt giá rẻ.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Chợ+đêm+Sơn+Trà"
  },
  {
    "name": "Sky36 Bar (Novotel Hotel)",
    "category": "Vui chơi",
    "address": "36 Bạch Đằng, Hải Châu, Đà Nẵng",
    "price_range": "200k - 500k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Quán bar sân thượng cao nhất Đà Nẵng sở hữu tầm nhìn 360 độ ngắm toàn thành phố lung linh trọn vẹn từ trên cao.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sky36+Đà+Nẵng"
  },
  {
    "name": "Công viên Châu Á (Asia Park - Sun Wheel)",
    "category": "Vui chơi",
    "address": "1 Phan Đăng Lưu, Hải Châu, Đà Nẵng",
    "price_range": "50k - 200k VND",
    "rating": 4.5,
    "tiktok_hot": true,
    "reason": "Công viên giải trí hiện đại với vòng quay Sun Wheel khổng lồ nằm trong top 10 vòng quay cao nhất thế giới.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Công+viên+Châu+Á"
  },
  {
    "name": "Phố đi bộ Bạch Đằng",
    "category": "Vui chơi",
    "address": "Đường Bạch Đằng, Hải Châu, Đà Nẵng",
    "price_range": "Miễn phí",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Tuyến đường đi bộ giáp sông Hàn lộng gió, thích hợp tản bộ thư thả thưởng thức kem hoặc xem nghệ sĩ đường phố trình diễn.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Phố+đi+bộ+Bạch+Đằng"
  },
  {
    "name": "On The Radio Bar",
    "category": "Vui chơi",
    "address": "76 Thái Phiên, Hải Châu, Đà Nẵng",
    "price_range": "50k - 150k VND",
    "rating": 4.6,
    "tiktok_hot": true,
    "reason": "Quán bar live-music đình đám của giới trẻ với ban nhạc cực chất biểu diễn rock, pop ballad cực đã tai mỗi tối.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=On+The+Radio+Bar+Đà+Nẵng"
  },
  {
    "name": "Chợ đêm Lê Duẩn",
    "category": "Vui chơi",
    "address": "Kiệt 144 Lê Duẩn, Hải Châu, Đà Nẵng",
    "price_range": "10k - 50k VND",
    "rating": 4.2,
    "tiktok_hot": false,
    "reason": "Khu chợ mua sắm quần áo giày dép giá sinh viên tấp nập trong lòng con phố trung tâm sầm uất.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Chợ+đêm+Lê+Duẩn"
  },
  {
    "name": "Draft Beer Bạch Đằng",
    "category": "Vui chơi",
    "address": "99 Bạch Đằng, Hải Châu, Đà Nẵng",
    "price_range": "100k - 300k VND",
    "rating": 4.5,
    "tiktok_hot": false,
    "reason": "Địa điểm tụ tập bạn bè uống bia tươi mát lạnh ngắm cảnh du thuyền sông Hàn lướt qua sống động.",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Draft+Beer+Bạch+Đằng"
  }
];

const EVENTS = [
  {
    "event_date": "27/06/2026",
    "event_name": "Lễ hội Pháo hoa Quốc tế Đà Nẵng (DIFF) 2026 - Đêm 5",
    "event_type": "Lễ hội",
    "start_time": "20:00",
    "end_time": "22:00",
    "location": "Khu vực Cảng Sông Hàn và vỉa hè đường Trần Hưng Đạo, Sơn Trà, Đà Nẵng",
    "ticket_price": "Từ 800.000đ - 3.000.000đ (Xem miễn phí từ xa dọc sông)",
    "description": "Đêm thi đấu thứ 5 mang chủ đề 'Tầm nhìn' (Vision) giữa hai đội Úc và Bồ Đào Nha. Trình diễn nghệ thuật ánh sáng và âm thanh hoành tráng bên sông Hàn.",
    "source_url": "https://danangfantasticity.com"
  },
  {
    "event_date": "27/06/2026",
    "event_name": "Lễ hội biển Đà Nẵng 2026 (An Hải Festival)",
    "event_type": "Lễ hội biển",
    "start_time": "16:00",
    "end_time": "18:00",
    "location": "Công viên Biển Đông và bãi biển Mỹ Khê, Sơn Trà, Đà Nẵng",
    "ticket_price": "Miễn phí",
    "description": "Chuỗi sự kiện 'Sóng Âm và Vị Giác', bao gồm hơn 100 gian hàng ẩm thực biển, đặc sản đường phố OCOP kết hợp không gian âm nhạc acoustic và DJ hiện đại.",
    "source_url": "https://danang.gov.vn"
  },
  {
    "event_date": "27/06/2026",
    "event_name": "Cầu Rồng phun lửa, phun nước",
    "event_type": "Trình diễn nghệ thuật",
    "start_time": "21:00",
    "end_time": "21:15",
    "location": "Cầu Rồng, đường Nguyễn Văn Linh, Hải Châu, Đà Nẵng",
    "ticket_price": "Miễn phí",
    "description": "Hoạt động trình diễn phun lửa (9 lần) và phun nước (3 lần) định kỳ mỗi cuối tuần (thứ Bảy & Chủ Nhật) thu hút đông đảo du khách.",
    "source_url": "https://danangfantasticity.com"
  },
  {
    "event_date": "28/06/2026",
    "event_name": "Cầu Rồng phun lửa, phun nước",
    "event_type": "Trình diễn nghệ thuật",
    "start_time": "21:00",
    "end_time": "21:15",
    "location": "Cầu Rồng, đường Nguyễn Văn Linh, Hải Châu, Đà Nẵng",
    "ticket_price": "Miễn phí",
    "description": "Hoạt động trình diễn phun lửa và phun nước định kỳ của biểu tượng thành phố biển Đà Nẵng.",
    "source_url": "https://danangfantasticity.com"
  }
];
